# Generated by Django 5.2.8 on 2026-01-19 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionsModel',
        ),
    ]
