# Generated by Django 5.2.8 on 2026-01-19 15:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionsmodel',
            name='user_id',
        ),
        migrations.AddField(
            model_name='transactionsmodel',
            name='user_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
